"""
Automation jobs executed by APScheduler.
Each job logs execution to automation_logs table.
"""
import asyncio
from datetime import datetime, timezone, date, timedelta
from app.db.session import AsyncSessionLocal
from app.models.product import Product
from app.models.purchase_order import PurchaseOrder, PurchaseOrderItem, POStatus
from app.models.supplier import Supplier
from app.models.report import AutomationLog, AutomationJobStatus, Report, ReportType
from sqlalchemy import select, func
from app.core.logging import logger


async def _log_job(db, job_name: str, status: AutomationJobStatus, message: str = None, details: dict = None):
    log = AutomationLog(
        job_name=job_name,
        status=status,
        message=message,
        details=details,
        completed_at=datetime.now(timezone.utc) if status != AutomationJobStatus.running else None,
    )
    db.add(log)
    await db.commit()


def run_daily_stock_alert():
    """Wrapper to run async job from APScheduler."""
    asyncio.create_task(_daily_stock_alert())


def run_weekly_report():
    asyncio.create_task(_weekly_report())


def run_expiry_alert():
    asyncio.create_task(_expiry_alert())


async def _daily_stock_alert():
    """
    JOB 1: Daily Stock Alert (8 AM)
    - Find low stock products
    - Auto-generate draft POs grouped by supplier category
    """
    job_name = "daily_stock_alert"
    logger.info("Starting job", job=job_name)

    async with AsyncSessionLocal() as db:
        try:
            # Find products below reorder threshold
            result = await db.execute(
                select(Product).where(
                    Product.is_active == True,
                    Product.stock < Product.reorder_threshold,
                )
            )
            low_stock = result.scalars().all()

            if not low_stock:
                await _log_job(db, job_name, AutomationJobStatus.success, "No low stock products found")
                return

            # Find a default supplier for auto-PO
            supplier_result = await db.execute(
                select(Supplier).where(Supplier.is_active == True).limit(1)
            )
            supplier = supplier_result.scalar_one_or_none()

            pos_created = []
            if supplier and low_stock:
                # Create one draft PO for all low stock items
                po = PurchaseOrder(
                    supplier_id=supplier.id,
                    status=POStatus.draft,
                    notes=f"Auto-generated by daily stock alert on {date.today()}",
                    created_by="automation",
                )
                db.add(po)
                await db.flush()

                total = 0.0
                for product in low_stock:
                    reorder_qty = max(product.reorder_threshold * 2 - product.stock, 1)
                    item = PurchaseOrderItem(
                        purchase_order_id=po.id,
                        product_id=product.id,
                        product_name=product.name,
                        sku=product.sku,
                        quantity=reorder_qty,
                        unit_price=product.price,
                        total_price=reorder_qty * product.price,
                    )
                    total += item.total_price
                    db.add(item)

                po.total_amount = total
                pos_created.append(po.id)

            await _log_job(
                db, job_name, AutomationJobStatus.success,
                f"Found {len(low_stock)} low stock products. Created {len(pos_created)} draft POs.",
                {"low_stock_count": len(low_stock), "po_ids": pos_created}
            )
            logger.info("Job completed", job=job_name, low_stock=len(low_stock))

        except Exception as e:
            logger.error("Job failed", job=job_name, error=str(e))
            await _log_job(db, job_name, AutomationJobStatus.failed, str(e))


async def _weekly_report():
    """
    JOB 2: Weekly Report (every Monday)
    - Sales summary from inventory logs
    - Top products by activity
    - Alerts summary
    """
    job_name = "weekly_report"
    logger.info("Starting job", job=job_name)

    async with AsyncSessionLocal() as db:
        try:
            from app.models.product import InventoryLog, InventoryChangeType

            week_ago = datetime.now(timezone.utc) - timedelta(days=7)

            # Total products
            product_count = await db.execute(
                select(func.count()).select_from(Product).where(Product.is_active == True)
            )

            # Low stock count
            low_stock_result = await db.execute(
                select(func.count()).select_from(Product).where(
                    Product.is_active == True,
                    Product.stock < Product.reorder_threshold,
                )
            )

            # POs this week
            po_result = await db.execute(
                select(func.count(), func.sum(PurchaseOrder.total_amount)).where(
                    PurchaseOrder.created_at >= week_ago
                )
            )
            po_stats = po_result.first()

            # Expiring products
            expiry_threshold = date.today() + timedelta(days=14)
            expiring_result = await db.execute(
                select(func.count()).select_from(Product).where(
                    Product.is_active == True,
                    Product.expiry_date != None,
                    Product.expiry_date <= expiry_threshold,
                    Product.expiry_date >= date.today(),
                )
            )

            report_content = {
                "week_ending": str(date.today()),
                "total_active_products": product_count.scalar(),
                "low_stock_products": low_stock_result.scalar(),
                "expiring_within_14_days": expiring_result.scalar(),
                "purchase_orders_this_week": po_stats[0] if po_stats else 0,
                "total_po_value_this_week": float(po_stats[1] or 0) if po_stats else 0,
            }

            report = Report(
                report_type=ReportType.weekly_summary,
                title=f"Weekly Inventory Report - {date.today()}",
                content=report_content,
            )
            db.add(report)

            await _log_job(
                db, job_name, AutomationJobStatus.success,
                "Weekly report generated", report_content
            )
            logger.info("Job completed", job=job_name)

        except Exception as e:
            logger.error("Job failed", job=job_name, error=str(e))
            await _log_job(db, job_name, AutomationJobStatus.failed, str(e))


async def _expiry_alert():
    """
    JOB 3: Expiry Alert (daily)
    - Find products expiring within 14 days
    - Log alert with recommended actions
    """
    job_name = "expiry_alert"
    logger.info("Starting job", job=job_name)

    async with AsyncSessionLocal() as db:
        try:
            threshold = date.today() + timedelta(days=14)
            result = await db.execute(
                select(Product).where(
                    Product.is_active == True,
                    Product.expiry_date != None,
                    Product.expiry_date <= threshold,
                    Product.expiry_date >= date.today(),
                )
            )
            expiring = result.scalars().all()

            details = {
                "checked_at": str(datetime.now(timezone.utc)),
                "threshold_days": 14,
                "expiring_products": [
                    {
                        "id": p.id,
                        "name": p.name,
                        "sku": p.sku,
                        "stock": p.stock,
                        "expiry_date": str(p.expiry_date),
                        "days_left": (p.expiry_date - date.today()).days,
                        "recommendation": "Discount / write-off" if (p.expiry_date - date.today()).days <= 3 else "Prioritize sales",
                    }
                    for p in expiring
                ]
            }

            if expiring:
                report = Report(
                    report_type=ReportType.expiry_alert,
                    title=f"Expiry Alert - {len(expiring)} products expiring within 14 days",
                    content=details,
                )
                db.add(report)

            await _log_job(
                db, job_name, AutomationJobStatus.success,
                f"Found {len(expiring)} products expiring within 14 days", details
            )
            logger.info("Job completed", job=job_name, expiring_count=len(expiring))

        except Exception as e:
            logger.error("Job failed", job=job_name, error=str(e))
            await _log_job(db, job_name, AutomationJobStatus.failed, str(e))